### ISSUE TITLE
Storybook環境で、デフォルトのフォントをFigma準拠の`  font-family: Inter, 'Noto Sans JP', sans-serif;`に指定する。

### ISSUE THREAD

**Issue by ReoHakase** [3I-shikosai32/shikosai32-front#153]
これを挿入する
```css
html,
body {
  font-family: Inter, 'Noto Sans JP', sans-serif;
}
```
Tailwindって`html, body`に対して`@apply`使えないんだっけ？
